version = 0.1
[default.deploy.parameters]
stack_name = "e2eragfileuploaded"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
resolve_s3 = true
s3_prefix = "e2eragfileuploaded"
parameter_overrides = "BucketName=\"e2e-rag-file-uploaded\""
image_repositories = []
